server.port=8082
spring.application.name=api-gateway

eureka.client.service-url.default-zone=http://localhost:8761/eureka/

gateway.routes.account.path=/accounts/**
gateway.routes.account.uri=lb://account-service

gateway.routes.loan.path=/loans/**
gateway.routes.loan.uri=lb://loan-service

gateway.routes.greet.path=/greet/**
gateway.routes.greet.uri=lb://greet-service
